enum class Quality(val intervals: List<Int>) {
    MAJOR(listOf(
            Constants.UNISON,
            Constants.MAJOR_THIRD,
            Constants.PERFECT_FIFTH
    )),
    MINOR(listOf(
            Constants.UNISON,
            Constants.MINOR_THIRD,
            Constants.PERFECT_FIFTH
    )),
    MAJOR_SEVENTH(listOf(
            Constants.UNISON,
            Constants.MAJOR_THIRD,
            Constants.PERFECT_FIFTH,
            Constants.MAJOR_SEVENTH
    )),
    MINOR_SEVENTH(listOf(
            Constants.UNISON,
            Constants.MINOR_THIRD,
            Constants.PERFECT_FIFTH,
            Constants.MINOR_SEVENTH
    )),
    DOMINANT_SEVENTH(listOf(
            Constants.UNISON,
            Constants.MAJOR_THIRD,
            Constants.PERFECT_FIFTH,
            Constants.MINOR_SEVENTH
    ))
}